/*
Deployment script for JWCSData

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "JWCSData"
:setvar DefaultFilePrefix "JWCSData"
:setvar DefaultDataPath "C:\db\mssql2017\MSSQL14.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\db\mssql2017\MSSQL14.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping [dbo].[FK_VendorTodo_Vendor]...';


GO
ALTER TABLE [dbo].[VendorTodo] DROP CONSTRAINT [FK_VendorTodo_Vendor];


GO
PRINT N'Dropping [dbo].[FK_VendorTodo_CreatedBy]...';


GO
ALTER TABLE [dbo].[VendorTodo] DROP CONSTRAINT [FK_VendorTodo_CreatedBy];


GO
PRINT N'Dropping [dbo].[FK_VendorTodo_UpdatedBy]...';


GO
ALTER TABLE [dbo].[VendorTodo] DROP CONSTRAINT [FK_VendorTodo_UpdatedBy];


GO
PRINT N'Starting rebuilding table [dbo].[VendorTodo]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_VendorTodo] (
    [Id]                    INT            IDENTITY (1, 1) NOT NULL,
    [VendorId]              INT            NOT NULL,
    [CreatedByVendorUserId] INT            NOT NULL,
    [UpdatedByVendorUserId] INT            NOT NULL,
    [Done]                  BIT            NOT NULL,
    [Title]                 NVARCHAR (MAX) NOT NULL,
    [ConcurrencyStamp]      NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[VendorTodo])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_VendorTodo] ON;
        INSERT INTO [dbo].[tmp_ms_xx_VendorTodo] ([Id], [VendorId], [CreatedByVendorUserId], [UpdatedByVendorUserId], [Done], [Title], [ConcurrencyStamp])
        SELECT   [Id],
                 [VendorId],
                 [CreatedByVendorUserId],
                 [UpdatedByVendorUserId],
                 [Done],
                 [Title],
                 [ConcurrencyStamp]
        FROM     [dbo].[VendorTodo]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_VendorTodo] OFF;
    END

DROP TABLE [dbo].[VendorTodo];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_VendorTodo]', N'VendorTodo';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[VendorTodo].[IX_VendorTodo_Vendor]...';


GO
CREATE NONCLUSTERED INDEX [IX_VendorTodo_Vendor]
    ON [dbo].[VendorTodo]([VendorId] ASC);


GO
PRINT N'Creating [dbo].[FK_VendorTodo_Vendor]...';


GO
ALTER TABLE [dbo].[VendorTodo] WITH NOCHECK
    ADD CONSTRAINT [FK_VendorTodo_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_VendorTodo_CreatedBy]...';


GO
ALTER TABLE [dbo].[VendorTodo] WITH NOCHECK
    ADD CONSTRAINT [FK_VendorTodo_CreatedBy] FOREIGN KEY ([CreatedByVendorUserId]) REFERENCES [dbo].[Vendor] ([Id]);


GO
PRINT N'Creating [dbo].[FK_VendorTodo_UpdatedBy]...';


GO
ALTER TABLE [dbo].[VendorTodo] WITH NOCHECK
    ADD CONSTRAINT [FK_VendorTodo_UpdatedBy] FOREIGN KEY ([UpdatedByVendorUserId]) REFERENCES [dbo].[Vendor] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[VendorTodo] WITH CHECK CHECK CONSTRAINT [FK_VendorTodo_Vendor];

ALTER TABLE [dbo].[VendorTodo] WITH CHECK CHECK CONSTRAINT [FK_VendorTodo_CreatedBy];

ALTER TABLE [dbo].[VendorTodo] WITH CHECK CHECK CONSTRAINT [FK_VendorTodo_UpdatedBy];


GO
PRINT N'Update complete.';


GO
