CREATE TABLE [dbo].[VendorUserToken](
	[UserId] INT NOT NULL,
	[LoginProvider] NVARCHAR(450) NOT NULL,
	[Name] NVARCHAR(450) NOT NULL,
	[Value] NVARCHAR(max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[VendorUserToken]  WITH CHECK ADD  CONSTRAINT [FK_VendorUserToken_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[VendorUser] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[VendorUserToken] CHECK CONSTRAINT [FK_VendorUserToken_UserId]
GO
ALTER TABLE [dbo].[VendorUserToken] ADD  CONSTRAINT [PK_VendorUserToken] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[LoginProvider] ASC,
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]