CREATE TABLE [dbo].[VendorAuthClaim](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClaimType] NVARCHAR(max) NULL,
	[ClaimValue] NVARCHAR(max) NULL,
	[Description] NVARCHAR(max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[VendorAuthClaim] ADD  CONSTRAINT [PK_VendorAuthClaim] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]