CREATE TABLE [dbo].[VendorUserRole](
	[UserId] INT NOT NULL,
	[RoleId] INT NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VendorUserRole]  WITH CHECK ADD  CONSTRAINT [FK_VendorUserRole_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[VendorAuthRole] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[VendorUserRole] CHECK CONSTRAINT [FK_VendorUserRole_RoleId]
GO
ALTER TABLE [dbo].[VendorUserRole]  WITH CHECK ADD  CONSTRAINT [FK_VendorUserRole_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[VendorUser] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[VendorUserRole] CHECK CONSTRAINT [FK_VendorUserRole_UserId]
GO
ALTER TABLE [dbo].[VendorUserRole] ADD  CONSTRAINT [PK_VendorUserRole] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_VendorUserRole_RoleId] ON [dbo].[VendorUserRole]
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]